### ISSUE TITLE
[Request] Make full image files available?

### ISSUE THREAD

**Issue by chadokruse** [dollaraday/dollaraday_template#1]
First, a sincere thank you for open sourcing all the great work and lessons learned behind Dollar A Day! I'm looking forward to seeing where the community takes it.

Question: Any chance you could include the full image files for the selected nonprofits? 

We're trying to help put as much nonprofit data out in the open as possible to make it easier for folks to hack on philanthropy. As you probably know, the primary sources of this data exist but are stuck behind paywalls and we'd like to change that.

We've already gathered the info on your 395 nonprofits and put them in machine-readable format (repo [here](https://github.com/smartergiving/open-data/blob/master/v0/curated_lists/dollar_a_day/all_data.json) - hope that's cool), but didn't want to go pulling [full image files](http://dollaraday.co/images/nonprofits/64/full.png) without your permission.

Thanks!

**Comment by cassiemarketos** [comment]
Hey Chad!

Great to hear from you — appreciate the interest! We're enthusiastic about
the idea of hacking on philanthropy, but do have concerns about the rights
to the images themselves, which we don't own. (We took them, mostly, from
the nonprofits Facebook pages or websites.) What exactly did you guys have
in mind to do with the images?

Let us know and thanks again for reaching out!

- Cass

**Comment by chadokruse** [comment]
No worries Cass, completely understand re: image rights. Just thought it would be fun to have folks, for example, carve up the 395 nonprofits that Dollar A Day selected into thematic lists (e.g. [gender equality](https://smartergiving.org/dispatch/lists/gender-equality/), environment, etc). Having the images would just save a little time, but no big deal.

**Comment by cassiemarketos** [comment]
Hey Chad,

We definitely agree — it would be fun! We would love to see something like
this work, but do you have any thoughts on why the image rights wouldn't be
a challenge? Would love to figure out a way to make it happen!

- Cass

**Comment by chadokruse** [comment]
I agree getting formal permission is the goal...would be great to seed a quality, open database of nonprofit identity data that any developer can rely on.

I'll do some thinking on how to automate the process, but in the meantime we might just have to do it manually. Our model focuses on lists of just ~10 nonprofits at a time, so reaching out to those 10 development directors individually isn't that difficult. Certainly open to suggestions though!

Also (while I've got you), curious about any lessons learned regarding the frequency of the Dollar A Day emails. We're always concerned with "donor giving fatigue", but have learned that quarterly contact isn't quite enough. Do you think a daily email was too much?

Thanks again Cass!

**Comment by cassiemarketos** [comment]
Hey Chad!

Thanks for getting back. I think it'd be best not to share the images, just
since we don't have explicit permission to be handing 'em over to people.
:)

As for the email frequency point. That was def an issue that we were
worried about, too. We felt people might get fatigued — then were surprised
to see that people really did regularly open + read the emails. (We had
something like a 50% open rate, although the data on that might be give or
take some percentage based on how accurate MailGun's data is, heh.) Think
the thing to keep in mind isn't necessarily frequency, but overall brevity.
Our emails came every day, but they were really digestible. Just bite-sized
little paragraphs about each nonprofit, so easy for people to open and
skim. That said, a digest option was definitely something we were
considering adding, for those who did prefer to scan weekly vs daily.

Let me know if you have any other Qs!

- Cass

**Comment by chadokruse** [comment]
Good stuff Cass...thanks for sharing!
